apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: e-commerce-zero-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: e-commerce-zero
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
